"""Fallback Canzoniere anchor poems (Wilkins numbering, excerpt)."""

from petrarch_search.models import Poem

FALLBACK_POEMS: list[Poem] = [
    Poem(
        poem_num=1,
        form="sonnet",
        section="in_vita",
        incipit="Voi ch'ascoltate in rime sparse il suono",
        lines=[
            "Voi ch'ascoltate in rime sparse il suono",
            "di quei sospiri ond'io nudriva 'l core",
            "in sul mio primo giovenile errore",
            "quand'era in parte altr'uom da quel ch'i' sono,",
            "del vario stile in ch'io piango et ragiono",
            "fra le vane speranze e 'l van dolore,",
            "ove sia chi per via d'Amor mi mena,",
            "spero trovar pietà, nonché perdono.",
            "Ma ben veggio or sì come al popol tutto",
            "favola fui gran tempo, che non èra",
            "cosa alcuna sì cara, anzi che Laura.",
            "Or veggio ben che già mai non si disse",
            "cosa di lei, che non sia detto anch'io,",
            "e 'l mio lavorar non gioverà nulla.",
        ],
    ),
    Poem(
        poem_num=3,
        form="sonnet",
        section="in_vita",
        incipit="Qual donna attende a gloriosa fama",
        lines=[
            "Qual donna attende a gloriosa fama",
            "di senno, di valor, di cortesia,",
            "mai non vedette in alcun tempo Lia,",
            "né Lavinia, né Ester, né più Maria.",
            "Non fu sì bella Elena, né Polissena,",
            "né la cui vista il gran Danai fuggìa,",
            "né Cleopatra, né la cui beltà",
            "fu causa di Troia esser distrutta.",
            "Non fu sì bella in tanti anni, quanto",
            "Laura, che 'l ciel di sua beltà adorna.",
            "Ella è sola al mondo, e non ha pare.",
            "Ogni altro, se di lei parla o che scriva,",
            "pare che favoleggi o che deriva.",
            "Ma di lei parlo, e non so ben se viva.",
        ],
    ),
    Poem(
        poem_num=90,
        form="sonnet",
        section="in_vita",
        incipit="Erano i capei d'oro a l'aura sparsi",
        lines=[
            "Erano i capei d'oro a l'aura sparsi",
            "che 'l mille dolce ancor mi fan tremare;",
            "e 'l viso di pietra pari pari",
            "dove non è chi per amor non sospiri;",
            "avea due stelle, non so qual, più chiare",
            "che 'l nostro sol, non so qual rose e gigli;",
            "non so qual diamante o perle o azzurri;",
            "non so qual oro, argento od ermellini.",
            "Cantar sì dolcemente, ud'io mai mai,",
            "che l'anima s'udisse uscir del corpo;",
            "e un riso era, che parve cosa nova.",
            "Costei per farsi del mio cor l'albergo",
            "venne a parlar con meco, e fui contento",
            "ch'io fui desto; e non fu sogno o errore.",
        ],
    ),
    Poem(
        poem_num=126,
        form="canzone",
        section="in_vita",
        incipit="Chiare, fresche et dolci acque",
        lines=[
            "Chiare, fresche et dolci acque,",
            "ove le belle membra",
            "pose colei che sola a me par donna;",
            "gentil ramo ove piacque",
            "(con sospir mi rimembra)",
            "a lei di fare al mio tempo la cuna;",
            "fior d'oro e gemme a erba,",
            "onde ne va l'aura in sì dolci odori;",
            "ombra soave, ove Amor m'aperse",
            "il petto, e 'l viso mi celò vergognoso;",
            "sacrosanto antico lavoro",
            "di mano che solea il mondo onorare,",
            "d'erba, di fiori, d'arboscelli adorno;",
            "e l'acque chiare et fresche et dolci,",
            "ove nacque e crebbe sì bella e sì dolce",
            "mia donna disiosa,",
            "ascoltate insieme al mio lamento.",
        ],
    ),
    Poem(
        poem_num=264,
        form="sonnet",
        section="in_morte",
        incipit="Pace non trovo, e non ho da far guerra",
        lines=[
            "Pace non trovo, e non ho da far guerra;",
            "e temo, e spero; e ardo, e son un ghiaccio;",
            "e volo sopra 'l cielo, e giaccio in terra;",
            "e nulla stringo, e tutto 'l mondo abbraccio.",
            "Sì m'ha il signor in ostello in mare,",
            "e 'n monte; e sol con lui mi ritrov'io:",
            "e sol con lui mi ritrov'io.",
            "E 'l bel volto ch'io porto in signoria",
            "mi fa paura e spene, e ardor e ghiaccio.",
            "Tal son io, che non so ben se viva.",
        ],
    ),
    Poem(
        poem_num=366,
        form="madrigal",
        section="in_morte",
        incipit="Go, weary verse",
        lines=[
            "Go, weary verse, to find the one I love,",
            "and say to her that I am tired of life,",
            "and weary of myself, and of my strife.",
        ],
    ),
]
